version: '3.7'

services: 
  db: 
    image: posgres:16.2
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: pos
    volumes: 
      - ./posgres:/var/lib/postgresql/data